from __future__ import annotations

from datetime import datetime
from typing import Protocol, Any

from signalflow.core.containers import Position, Trade, Portfolio
from signalflow.strategy.component.base import SfComponentType


class StrategyStore(Protocol):
    component_type: SfComponentType = SfComponentType.STRATEGY_STORE

    def ensure_schema(self) -> None: ...
    def close(self) -> None: ...

    # portfolio state
    def load_portfolio(self, strategy_id: str) -> Portfolio: ...
    def save_portfolio(self, strategy_id: str, portfolio: Portfolio) -> None: ...

    # positions
    def load_open_positions(self, strategy_id: str) -> list[Position]: ...
    def upsert_positions(self, strategy_id: str, positions: list[Position]) -> None: ...
    def close_positions(self, strategy_id: str, position_ids: list[str], ts: datetime, reason: str) -> None: ...

    # trades
    def insert_trades(self, strategy_id: str, trades: list[Trade]) -> None: ...

    # metrics
    def insert_metrics(self, strategy_id: str, ts: datetime, values: dict[str, float]) -> None: ...

    # key-value (runner/engine state)
    def kv_get(self, strategy_id: str, key: str) -> str | None: ...
    def kv_set(self, strategy_id: str, key: str, value: str) -> None: ...
